### ISSUE TITLE
Installation on Pi1 fails

### ISSUE THREAD

**Issue by he-so** [AlCalzone/node-aead-crypto#11]
When installing iobroker.tradfri or iobroker.sonoff that depend on this module, the installation of node-aead-crypto fails.

OS is a plain Raspbian Stretch with nodejs 8 installed from tarball.

```0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'install:rpi1' ]
2 info using npm@6.4.1
3 info using node@v8.15.0
4 verbose run-script [ 'preinstall:rpi1', 'install:rpi1', 'postinstall:rpi1' ]
5 info lifecycle node-aead-crypto@2.1.4~preinstall:rpi1: node-aead-crypto@2.1.4
6 info lifecycle node-aead-crypto@2.1.4~install:rpi1: node-aead-crypto@2.1.4
7 verbose lifecycle node-aead-crypto@2.1.4~install:rpi1: unsafe-perm in lifecycle true
8 verbose lifecycle node-aead-crypto@2.1.4~install:rpi1: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/opt/iobroker/node_modules/node-aead-crypto/node_modules/.bin:/opt/iobroker/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/opt/iobroker/node_modules/node-aead-crypto/node_modules/.bin:/opt/iobroker/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle node-aead-crypto@2.1.4~install:rpi1: CWD: /opt/iobroker/node_modules/node-aead-crypto
10 silly lifecycle node-aead-crypto@2.1.4~install:rpi1: Args: [ '-c', 'prebuild-install --build-from-source' ]
11 silly lifecycle node-aead-crypto@2.1.4~install:rpi1: Returned: code: 1  signal: null
12 info lifecycle node-aead-crypto@2.1.4~install:rpi1: Failed to exec install:rpi1 script
13 verbose stack Error: node-aead-crypto@2.1.4 install:rpi1: `prebuild-install --build-from-source`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:915:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid node-aead-crypto@2.1.4
15 verbose cwd /opt/iobroker/node_modules/node-aead-crypto
16 verbose Linux 4.14.79+
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "install:rpi1"
18 verbose node v8.15.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error node-aead-crypto@2.1.4 install:rpi1: `prebuild-install --build-from-source`
22 error Exit status 1
23 error Failed at the node-aead-crypto@2.1.4 install:rpi1 script.
```

**Comment by AlCalzone** [comment]
I don't see the interesting part of the error message. Can you please try to install one of the adapters via the console and share the output?
```
cd /opt/iobroker 
npm i iobroker.tradfri
```

**Comment by he-so** [comment]
meanwhile I have upgraded to node 10 that works without this aead-crypto.
But I found this in the logs when I was using node 8:
```
2019-01-10 17:27:22.516  - info: iobroker npm install iobroker.tradfri --production --save --prefix "/opt/iobroker" (System call)
2019-01-10 17:33:07.717  - info: iobroker npm
2019-01-10 17:33:07.749  - info: iobroker  ERR! code ELIFECYCLEnpm ERR! errno 1

2019-01-10 17:33:07.801  - info: iobroker npm
2019-01-10 17:33:07.823  - info: iobroker  ERR! node-aead-crypto@2.1.4 install:rpi1: `prebuild-install --build-from-source`
2019-01-10 17:33:07.846  - info: iobroker npm ERR! Exit status 1npm ERR!
npm
2019-01-10 17:33:07.876  - info: iobroker  ERR! Failed at the node-aead-crypto@2.1.4 install:rpi1 script.npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

2019-01-10 17:33:08.002  - info: iobroker
2019-01-10 17:33:08.015  - info: iobroker npm
2019-01-10 17:33:08.034  - info: iobroker  ERR! A complete log of this run can be found in:npm ERR!     /home/iobroker/.npm/_logs/2019-01-10T16_33_07_934Z-debug.log

2019-01-10 17:33:08.102  - info: iobroker child_process.js:650    throw err;
    ^

Error: Command failed: npm run install:rpi1
    at checkExecSyncError (child_process.js:607:13)
    at execSync (child_process.js:647:13)
    at Object.<anonymous> (/opt/iobroker/node_modules/node-aead-crypto/lib/install.js:29:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)

2019-01-10 17:33:37.807  - info: iobroker npm
2019-01-10 17:33:37.823  - info: iobroker
2019-01-10 17:33:37.854  - info: iobroker WARN optional SKIPPING OPTIONAL DEPENDENCY: node-aead-crypto@2.1.4 (node_modules/node-aead-crypto):npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-aead-crypto@2.1.4 install: `node lib/install.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1


2019-01-10 17:33:38.299  - info: iobroker host.raspberrypi install adapter tradfri
2019-01-10 17:33:38.444  - info: iobroker got /opt/iobroker/node_modules/iobroker.tradfri/admin
2019-01-10 17:33:38.486  - info: iobroker upload [20] tradfri.admin /opt/iobroker/node_modules/iobroker.tradfri/admin/words.js words.js application/javascript
```

**Comment by AlCalzone** [comment]
Just out of curiosity, could you upload that logfile that is mentioned in the excerpt you pasted here?

**Comment by he-so** [comment]
Yes, that was the log I pasted in the first post.

**Comment by AlCalzone** [comment]
Hmm. I cannot find the error - just that one happened 🤔

**Comment by AlCalzone** [comment]
As this package will be obsolete at the end of this year, I'm not going to spend time debugging and fixing this issue.
